# These are supported funding model platforms

github: bsv-blockchain
custom: https://mrz1818.com/?tab=tips&utm_source=github&utm_medium=sponsor-link&utm_campaign=go-wire&utm_term=go-wire&utm_content=go-wire
