repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v1.3.0
    hooks:
      - id: gofmt
      - id: goimports
      - id: govet
      - id: golangci-lint
        args: ["--config=.golangci.json"]
      - id: go-unit-tests
        args: ["-v", "./..."]

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go-mod-tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
